version: '2'
services:
    kotlinster-app:
        image: kotlinster
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://kotlinster-postgresql:5432/kotlinster
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    kotlinster-postgresql:
        extends:
            file: postgresql.yml
            service: kotlinster-postgresql
